/* eslint-disable @typescript-eslint/no-misused-promises */
import Head from "next/head";
import ConnectWallet from "~/components/Header/ConnectWallet";
import Header from "~/components/Header/Header";
import Logo from "~/components/Header/Logo";
import Menu from "~/components/Header/Menu";
import Layout from "~/components/Layouts/Layout";

export default function Home() {
  return (
    <>
      <Head>
        <title></title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header>
        <Logo />
        <Menu />
        <ConnectWallet />
      </Header>
    </>
  );
}
